/*
 * File: app/view/PostForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ChatDawg40.view.PostForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.postform',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 250,
    itemId: 'postForm',
    width: 400,
    title: 'Post',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 10 0',
                            fieldLabel: 'Name',
                            labelAlign: 'right',
                            msgTarget: 'title',
                            name: 'post',
                            allowBlank: false,
                            blankText: 'Enter your full name.'
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'postButton',
                            scale: 'medium',
                            text: 'Post'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});